spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/accountdb  
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQLDialect   
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
      name: account-service
server:
   port: 9000
   error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: refresh
customProperty:
  test: ThorRagnarok
