spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: account-service
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
customProperty:
  test: Thor
api:
  customer: http://CUSTOMER-SERVICE/customer
