spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQLDialect   
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
      name: customer-service
server:
   port: 0
   error:
    include-message: always
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
